### User sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Aniket",
    "company":"UPMRC",
    "address": "something",
    "phone": "1234567890",
    "email": "ak4̥@gmail.com",
    "password":"secret123"

}

### User sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "ak2@gmail.com",
    "password":"secret123"

}

### User profile endpoint
GET http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFrMkBnbWFpbC5jb20iLCJpYXQiOjE3NTExODgwODQsImV4cCI6MTc1MTE4ODk4NH0.Sr-XKnyyN_1JgU3nx6yC6x1SGBm28kphA9ECzx-9rkc

### Token router

### Get refresh tokens
GET http://localhost:3001/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFrMkBnbWFpbC5jb20iLCJpYXQiOjE3NTExODc2MTIsImV4cCI6MTc1Mzc3OTYxMn0.-vingw2LcW0bZ28bJur0ZRIY2sXFrFNAZ1OR-CnjAu8